version: '2'
services:

  consul:
    image: "consul"
    hostname: "consul"
    command: "agent -server -bind 0.0.0.0 -client 0.0.0.0 -bootstrap-expect=1 -ui"
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"

  vault:
    depends_on:
      - consul
    image: "vault"
    hostname: "vault"
    links:
      - "consul:consul"
    environment:
      VAULT_ADDR: http://127.0.0.1:8200
    ports:
      - "8200:8200"
    volumes:
      - ./tools/wait-for-it.sh:/wait-for-it.sh
      - ./config/vault:/config
      - ./config/vault/policies:/policies
    entrypoint: /wait-for-it.sh -t 20 -h consul -p 8500 -s -- vault server -config=/config/with-consul.hcl

  client:
    image: "consul-client"
    hostname: "client"
    links:
      - "consul:consul"
      - "vault:vault"
    build:
      context: .
      dockerfile: Dockerfile-client
    environment:
      VAULT_ADDR: http://vault:8200
      CONSUL_HTTP_ADDR: consul:8500
    volumes:
      - ./arctools:/mnt/data
    entrypoint: consul agent -data-dir=/tmp/ -retry-join consul
